repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-symlinks
          - id: check-toml
          - id: mixed-line-ending
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: go-fmt
          - id: go-imports
          - id: no-go-testing
          - id: golangci-lint
          - id: go-unit-tests
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.22.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ["@commitlint/config-conventional"]
    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.7
      hooks:
          - id: actionlint
    - repo: https://github.com/trufflesecurity/truffleHog
      rev: v3.88.29
      hooks:
          - id: trufflehog
    - repo: https://github.com/mrtazz/checkmake
      rev: 0.2.2
      hooks:
          - id: checkmake
    - repo: https://github.com/openstack/bashate
      rev: 2.1.1
      hooks:
          - id: bashate
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
