// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"context"

	"github.com/arustydev/goslings/internal/auth/shared"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockStore
func (_mock *MockStore) Clear(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockStore_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx
func (_e *MockStore_Expecter) Clear(ctx interface{}) *MockStore_Clear_Call {
	return &MockStore_Clear_Call{Call: _e.mock.On("Clear", ctx)}
}

func (_c *MockStore_Clear_Call) Run(run func(ctx context.Context)) *MockStore_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_Clear_Call) Return(err error) *MockStore_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Clear_Call) RunAndReturn(run func(ctx context.Context) error) *MockStore_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCredentials provides a mock function for the type MockStore
func (_mock *MockStore) LoadCredentials(ctx context.Context) (*shared.Credentials, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadCredentials")
	}

	var r0 *shared.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*shared.Credentials, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *shared.Credentials); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shared.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_LoadCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCredentials'
type MockStore_LoadCredentials_Call struct {
	*mock.Call
}

// LoadCredentials is a helper method to define mock.On call
//   - ctx
func (_e *MockStore_Expecter) LoadCredentials(ctx interface{}) *MockStore_LoadCredentials_Call {
	return &MockStore_LoadCredentials_Call{Call: _e.mock.On("LoadCredentials", ctx)}
}

func (_c *MockStore_LoadCredentials_Call) Run(run func(ctx context.Context)) *MockStore_LoadCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_LoadCredentials_Call) Return(credentials *shared.Credentials, err error) *MockStore_LoadCredentials_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *MockStore_LoadCredentials_Call) RunAndReturn(run func(ctx context.Context) (*shared.Credentials, error)) *MockStore_LoadCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// LoadM365Resources provides a mock function for the type MockStore
func (_mock *MockStore) LoadM365Resources(ctx context.Context) (*shared.M365Resources, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadM365Resources")
	}

	var r0 *shared.M365Resources
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*shared.M365Resources, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *shared.M365Resources); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shared.M365Resources)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_LoadM365Resources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadM365Resources'
type MockStore_LoadM365Resources_Call struct {
	*mock.Call
}

// LoadM365Resources is a helper method to define mock.On call
//   - ctx
func (_e *MockStore_Expecter) LoadM365Resources(ctx interface{}) *MockStore_LoadM365Resources_Call {
	return &MockStore_LoadM365Resources_Call{Call: _e.mock.On("LoadM365Resources", ctx)}
}

func (_c *MockStore_LoadM365Resources_Call) Run(run func(ctx context.Context)) *MockStore_LoadM365Resources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_LoadM365Resources_Call) Return(m365Resources *shared.M365Resources, err error) *MockStore_LoadM365Resources_Call {
	_c.Call.Return(m365Resources, err)
	return _c
}

func (_c *MockStore_LoadM365Resources_Call) RunAndReturn(run func(ctx context.Context) (*shared.M365Resources, error)) *MockStore_LoadM365Resources_Call {
	_c.Call.Return(run)
	return _c
}

// LoadParams provides a mock function for the type MockStore
func (_mock *MockStore) LoadParams(ctx context.Context) (*shared.AuthParams, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadParams")
	}

	var r0 *shared.AuthParams
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*shared.AuthParams, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *shared.AuthParams); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shared.AuthParams)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_LoadParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadParams'
type MockStore_LoadParams_Call struct {
	*mock.Call
}

// LoadParams is a helper method to define mock.On call
//   - ctx
func (_e *MockStore_Expecter) LoadParams(ctx interface{}) *MockStore_LoadParams_Call {
	return &MockStore_LoadParams_Call{Call: _e.mock.On("LoadParams", ctx)}
}

func (_c *MockStore_LoadParams_Call) Run(run func(ctx context.Context)) *MockStore_LoadParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_LoadParams_Call) Return(authParams *shared.AuthParams, err error) *MockStore_LoadParams_Call {
	_c.Call.Return(authParams, err)
	return _c
}

func (_c *MockStore_LoadParams_Call) RunAndReturn(run func(ctx context.Context) (*shared.AuthParams, error)) *MockStore_LoadParams_Call {
	_c.Call.Return(run)
	return _c
}

// StoreCredentials provides a mock function for the type MockStore
func (_mock *MockStore) StoreCredentials(ctx context.Context, creds *shared.Credentials) error {
	ret := _mock.Called(ctx, creds)

	if len(ret) == 0 {
		panic("no return value specified for StoreCredentials")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *shared.Credentials) error); ok {
		r0 = returnFunc(ctx, creds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_StoreCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreCredentials'
type MockStore_StoreCredentials_Call struct {
	*mock.Call
}

// StoreCredentials is a helper method to define mock.On call
//   - ctx
//   - creds
func (_e *MockStore_Expecter) StoreCredentials(ctx interface{}, creds interface{}) *MockStore_StoreCredentials_Call {
	return &MockStore_StoreCredentials_Call{Call: _e.mock.On("StoreCredentials", ctx, creds)}
}

func (_c *MockStore_StoreCredentials_Call) Run(run func(ctx context.Context, creds *shared.Credentials)) *MockStore_StoreCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*shared.Credentials))
	})
	return _c
}

func (_c *MockStore_StoreCredentials_Call) Return(err error) *MockStore_StoreCredentials_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_StoreCredentials_Call) RunAndReturn(run func(ctx context.Context, creds *shared.Credentials) error) *MockStore_StoreCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// StoreM365Resources provides a mock function for the type MockStore
func (_mock *MockStore) StoreM365Resources(ctx context.Context, resources *shared.M365Resources) error {
	ret := _mock.Called(ctx, resources)

	if len(ret) == 0 {
		panic("no return value specified for StoreM365Resources")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *shared.M365Resources) error); ok {
		r0 = returnFunc(ctx, resources)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_StoreM365Resources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreM365Resources'
type MockStore_StoreM365Resources_Call struct {
	*mock.Call
}

// StoreM365Resources is a helper method to define mock.On call
//   - ctx
//   - resources
func (_e *MockStore_Expecter) StoreM365Resources(ctx interface{}, resources interface{}) *MockStore_StoreM365Resources_Call {
	return &MockStore_StoreM365Resources_Call{Call: _e.mock.On("StoreM365Resources", ctx, resources)}
}

func (_c *MockStore_StoreM365Resources_Call) Run(run func(ctx context.Context, resources *shared.M365Resources)) *MockStore_StoreM365Resources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*shared.M365Resources))
	})
	return _c
}

func (_c *MockStore_StoreM365Resources_Call) Return(err error) *MockStore_StoreM365Resources_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_StoreM365Resources_Call) RunAndReturn(run func(ctx context.Context, resources *shared.M365Resources) error) *MockStore_StoreM365Resources_Call {
	_c.Call.Return(run)
	return _c
}

// StoreParams provides a mock function for the type MockStore
func (_mock *MockStore) StoreParams(ctx context.Context, params *shared.AuthParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for StoreParams")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *shared.AuthParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_StoreParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreParams'
type MockStore_StoreParams_Call struct {
	*mock.Call
}

// StoreParams is a helper method to define mock.On call
//   - ctx
//   - params
func (_e *MockStore_Expecter) StoreParams(ctx interface{}, params interface{}) *MockStore_StoreParams_Call {
	return &MockStore_StoreParams_Call{Call: _e.mock.On("StoreParams", ctx, params)}
}

func (_c *MockStore_StoreParams_Call) Run(run func(ctx context.Context, params *shared.AuthParams)) *MockStore_StoreParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*shared.AuthParams))
	})
	return _c
}

func (_c *MockStore_StoreParams_Call) Return(err error) *MockStore_StoreParams_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_StoreParams_Call) RunAndReturn(run func(ctx context.Context, params *shared.AuthParams) error) *MockStore_StoreParams_Call {
	_c.Call.Return(run)
	return _c
}
